repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.28.0
  hooks:
  - id: pyproject-fmt
    language_version: python3.13
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.3
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.29.0
  hooks:
  - id: zizmor
    language_version: python3.13
    args: [--fix=safe, --offline]
