[build-system]
build-backend = "flit_core.buildapi"
requires = [
  "flit-core>=3.2,<4",
]

[project]
name = "ctypes-windows-sdk"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Dobatymo", email = "Dobatymo@users.noreply.github.com" },
]
requires-python = ">=3.7"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: ISC License (ISCL)",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development",
  "Topic :: System :: Operating System",

]
dynamic = [
  "description",
  "version",
]
urls.Homepage = "https://github.com/Dobatymo/ctypes-windows-sdk"

[tool.flit.module]
name = "cwinsdk"

[tool.ruff]
line-length = 120
lint.extend-select = [
  "B",
  "C4",
  "DTZ",
  "I",
  "PIE",
  "RUF",
  "S",
  "SIM",
  "UP",
]
lint.ignore = [
  "E741",
  "RUF012",
  "S101",
]
lint.per-file-ignores."cwinsdk/__init__.py" = [
  "RUF005",
]

lint.per-file-ignores."cwinsdk/windows.py" = [
  "F403",
]

[tool.mypy]
allow_redefinition = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
