from ctypes import POINTER, Structure, Union, c_uint16, c_uint32, c_uint64

from .. import CEnum
from .guiddef import GUID
from .ntdef import ULONG

NET_IF_COMPARTMENT_ID = c_uint32
PNET_IF_COMPARTMENT_ID = POINTER(NET_IF_COMPARTMENT_ID)
NET_IF_NETWORK_GUID = GUID
PNET_IF_NETWORK_GUID = POINTER(NET_IF_NETWORK_GUID)


class NET_IF_OPER_STATUS(CEnum):
    NET_IF_OPER_STATUS_UP = 1
    NET_IF_OPER_STATUS_DOWN = 2
    NET_IF_OPER_STATUS_TESTING = 3
    NET_IF_OPER_STATUS_UNKNOWN = 4
    NET_IF_OPER_STATUS_DORMANT = 5
    NET_IF_OPER_STATUS_NOT_PRESENT = 6
    NET_IF_OPER_STATUS_LOWER_LAYER_DOWN = 7


PNET_IF_OPER_STATUS = POINTER(NET_IF_OPER_STATUS)
NET_IF_OBJECT_ID = c_uint32
PNET_IF_OBJECT_ID = POINTER(NET_IF_OBJECT_ID)


class NET_IF_ADMIN_STATUS(CEnum):
    NET_IF_ADMIN_STATUS_UP = 1
    NET_IF_ADMIN_STATUS_DOWN = 2
    NET_IF_ADMIN_STATUS_TESTING = 3


PNET_IF_ADMIN_STATUS = POINTER(NET_IF_ADMIN_STATUS)


class NET_LUID_INFO(Structure):
    _fields_ = [
        ("Reserved", c_uint64, 24),
        ("NetLuidIndex", c_uint64, 24),
        ("IfType", c_uint64, 16),
    ]


class NET_LUID_LH(Union):
    _fields_ = [("Value", c_uint64), ("Info", NET_LUID_INFO)]


PNET_LUID_LH = POINTER(NET_LUID_LH)
NET_LUID = NET_LUID_LH
PNET_LUID = POINTER(NET_LUID)
IF_LUID = NET_LUID
PIF_LUID = POINTER(IF_LUID)

NET_IFINDEX = ULONG
PNET_IFINDEX = POINTER(NET_IFINDEX)
NET_IFTYPE = c_uint16
PNET_IFTYPE = POINTER(NET_IFTYPE)
IF_INDEX = NET_IFINDEX
PIF_INDEX = POINTER(IF_INDEX)


class NET_IF_CONNECTION_TYPE(CEnum):
    NET_IF_CONNECTION_DEDICATED = 1
    NET_IF_CONNECTION_PASSIVE = 2
    NET_IF_CONNECTION_DEMAND = 3
    NET_IF_CONNECTION_MAXIMUM = 4


PNET_IF_CONNECTION_TYPE = POINTER(NET_IF_CONNECTION_TYPE)


class TUNNEL_TYPE(CEnum):
    TUNNEL_TYPE_NONE = 0
    TUNNEL_TYPE_OTHER = 1
    TUNNEL_TYPE_DIRECT = 2
    TUNNEL_TYPE_6TO4 = 11
    TUNNEL_TYPE_ISATAP = 13
    TUNNEL_TYPE_TEREDO = 14
    TUNNEL_TYPE_IPHTTPS = 15


PTUNNEL_TYPE = POINTER(TUNNEL_TYPE)
