from .. import CEnum
from .ntdef import ULONG

IFTYPE = ULONG


class IF_ACCESS_TYPE(CEnum):
    IF_ACCESS_LOOPBACK = 1
    IF_ACCESS_BROADCAST = 2
    IF_ACCESS_POINT_TO_POINT = 3
    IF_ACCESS_POINTTOPOINT = 3
    IF_ACCESS_POINT_TO_MULTI_POINT = 4
    IF_ACCESS_POINTTOMULTIPOINT = 4


class INTERNAL_IF_OPER_STATUS(CEnum):
    IF_OPER_STATUS_NON_OPERATIONAL = 0
    IF_OPER_STATUS_UNREACHABLE = 1
    IF_OPER_STATUS_DISCONNECTED = 2
    IF_OPER_STATUS_CONNECTING = 3
    IF_OPER_STATUS_CONNECTED = 4
    IF_OPER_STATUS_OPERATIONAL = 5


class IF_OPER_STATUS(CEnum):
    IfOperStatusUp = 1
    IfOperStatusDown = 2
    IfOperStatusTesting = 3
    IfOperStatusUnknown = 4
    IfOperStatusDormant = 5
    IfOperStatusNotPresent = 6
    IfOperStatusLowerLayerDown = 7


MAXLEN_PHYSADDR = 8
MAXLEN_IFDESCR = 256
MAX_INTERFACE_NAME_LEN = 256

MIB_IF_ADMIN_STATUS_UP = 1
MIB_IF_ADMIN_STATUS_DOWN = 2
MIB_IF_ADMIN_STATUS_TESTING = 3
