# Define SRB types supported
SRB_TYPE_SCSI_REQUEST_BLOCK = 0
SRB_TYPE_STORAGE_REQUEST_BLOCK = 1
SRB_TYPE_NVME_REQUEST_BLOCK = 2

# Define address type supported
STORAGE_ADDRESS_TYPE_BTL8 = 0
STORAGE_ADDRESS_TYPE_NVME = 1
